name: 'publish-api-image'
description: 'Publish API Image to AWS ECR'

inputs:
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
    default: './Dockerfile'

  main-class:
    description: 'Main class or entry point for the Java application'
    required: true
    default: 'fplarache.smartlib.notifications'

  image-short-name:
    description: 'Short name of the Docker image'
    required: true
    default: 'dev-fpl-larache-smart-lib'

  image-prefix:
    description: 'Prefix for the Docker image'
    required: true
    default: 'service-notification-repo'

  image-tag:
    description: 'Tag for the Docker image'
    required: true
    default: 'v1.0.0'

  ecr-registry:
    description: 'AWS ECR registry'
    required: true
    default: '774305596814.dkr.ecr.eu-north-1.amazonaws.com'

runs:
  using: "composite"
  steps:
    - name: Build Java project with Maven
      shell: bash
      run: mvn clean package -DskipTests

    - name: Build Docker image
      shell: bash
      run: |
        IMAGENAME=${{ inputs.ecr-registry }}/${{ inputs.image-prefix }}-${{ inputs.image-short-name }}
        docker build \
          --build-arg JAVA_MAIN_CLASS=${{ inputs.main-class }} \
          -f ${{ inputs.dockerfile }} \
          -t $IMAGENAME:${{ inputs.image-tag }} .
        echo "Docker image built: $IMAGENAME:${{ inputs.image-tag }}"

    - name: Tag Docker image
      shell: bash
      run: |
        IMAGENAME=${{ inputs.ecr-registry }}/${{ inputs.image-prefix }}-${{ inputs.image-short-name }}
        docker tag $IMAGENAME:${{ inputs.image-tag }} $IMAGENAME:latest

    - name: Push Docker image to ECR
      shell: bash
      run: |
        IMAGENAME=${{ inputs.ecr-registry }}/${{ inputs.image-prefix }}-${{ inputs.image-short-name }}
        docker push $IMAGENAME:${{ inputs.image-tag }}
        docker push $IMAGENAME:latest
