name: Deploy Java Application

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-dev"
      - "v[0-9]+.[0-9]+.[0-9]+-prod"

jobs:
  deploy:
    name: "Deploy Java Application"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_ADMIN_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_ADMIN_AWS_SECRET_KEY }}
          aws-region: "eu-north-1"

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Publish Docker image
        uses: ./.github/actions/publish-api-image
        with:
          dockerfile: './Dockerfile'
          main-class: 'fplarache.smartlib.notifications'
          image-short-name: 'notification-service'
          image-prefix: 'smartlib'
          image-tag: ${{ github.sha }}
          ecr-registry: '774305596814.dkr.ecr.eu-north-1.amazonaws.com'

      - name: Deploy to ECS
        env:
          ECS_CLUSTER: ${{ github.ref_name }}-fgcluster
          ECS_SERVICE: ${{ github.ref_name }}-fgservice
        run: |
          echo "Deploying to ECS..."
          aws ecs update-service \
            --cluster ${ECS_CLUSTER} \
            --service ${ECS_SERVICE} \
            --force-new-deployment
          echo "ECS deployment triggered successfully."
